name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+.[a-zA-Z0-9]+'

jobs:
  build:
    runs-on: macos-latest
    concurrency:
      group: publish-${{ inputs.build_branch }}
      cancel-in-progress: false
    permissions:
      contents: read
    env:
      RELEASE_VERSION: ${{ github.ref_name }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.BRIGHTIFY_MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.BRIGHTIFY_MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.BRIGHTIFY_SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.BRIGHTIFY_SIGNING_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.BRIGHTIFY_SIGNING_KEY }}
      ORG_GRADLE_PROJECT_intellijPublishToken: ${{ secrets.BRIGHTIFY_INTELLIJ_PUBLISH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Cache build tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('**/*.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties', '**/libs.versions.toml') }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Xcode?
        run: xcode-select -p
      - name: Publish to Maven Central
        run: ./gradlew -p sources -PenableCompose publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace
      - name: Publish to Gradle Plugins
        run: ./gradlew -p sources publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} --stacktrace
      - name: Publish IDE plugins
        run: ./gradlew -p sources publishPlugin --stacktrace
