# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read


env: # Or as an environment variable
  ORG_GRADLE_PROJECT_brightifyUsername: ${{ secrets.ORG_GRADLE_PROJECT_brightifyUsername }}
  ORG_GRADLE_PROJECT_brightifyPassword: ${{ secrets.ORG_GRADLE_PROJECT_brightifyPassword }}

jobs:
  build:
    runs-on: macos-latest
    concurrency:
      group: tests-${{ inputs.build_branch }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Cache build tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('**/*.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties', '**/libs.versions.toml') }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Xcode?
        run: xcode-select -p
      - name: Build
        run: ./gradlew -p sources build
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        if: ${{ false && failure() }}
